apiVersion: v1
items:
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: git-source
  spec:
    params:
    - name: revision
      value: master
    - name: url
      value: https://github.ibm.com/aadeshpa/java-microprofile-app-war-pipeline.git 
    type: git
kind: List